name: Compile PS2 Project

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build ELF
        run: |
          make

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ps2_rpgmaker_elf
          path: ps2_rpgmaker.elf
